### ISSUE TITLE
Como hago para  modificar un apk y ponerle el payload 

### ISSUE THREAD

**Issue by mjuanxd** [byteSalgado/msfpayload#1]
Como va? estaba usando tu script que está piola pero no se como tengo que hacer para ponerle el payload a una app legitima, me podrias guiar maso menos?
Gracias bro

**Comment by FacuSecX** [comment]
Hola, Juan. Para infectar el APK legitima primero debes descargar el .APK y ponerlo en la carpeta del SCRIPT.. despues inicias el script y seleccionas la RUTA donde tenes el .apk original. Despues seguis las instrucciones del SCRIPT y podras recompilar la App con el backdoor adentro. Cabe aclarar que no todas las aplicaciones son vulnerables a la inyeccion de carga util. Si no te funciona con alguna APP en particular que quieras infectar proba con otra distinta.
